# Generated by Django 4.0.6 on 2022-08-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobby', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
