# Generated by Django 4.0.6 on 2022-08-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interest', '0002_technical_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technical_skills',
        ),
    ]
